version: '3.8'
x-kong-config: &kong-env
  KONG_DATABASE: ${KONG_DATABASE:-postgres}
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
services:
  # --- Postgres ---
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- Redis ---
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # --- Elasticsearch ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  # --- RabbitMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # --- Kong ---
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    profiles: ["database"]
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - microservices_network
    restart: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    profiles: ["database"]
    depends_on:
      - db
    environment:
      <<: *kong-env
    secrets:
      - kong_postgres_password
    networks:
      - microservices_network
    restart: on-failure

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    environment:
      <<: *kong-env
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "${KONG_PROXY_LISTEN:-0.0.0.0:8000}"
      KONG_ADMIN_LISTEN: "${KONG_ADMIN_LISTEN:-0.0.0.0:8001}"
      KONG_ADMIN_GUI_LISTEN: "${KONG_ADMIN_GUI_LISTEN:-0.0.0.0:8002}"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    secrets:
      - kong_postgres_password
    networks:
      - microservices_network
    ports:
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    read_only: true
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
      - ./kong-gateway/config:/opt/kong
    security_opt:
      - no-new-privileges
  db:
    image: postgres:9.5
    profiles: ["database"]
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: "kong"
    secrets:
      - kong_postgres_password
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - microservices_network
    volumes:
      - kong_data:/var/lib/postgresql/data
  
    
  # --- Microservices ---
  auth-service:
    build: ../../services/auth-service
    volumes:
      - ../../services/auth-service:/app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: auth-service
      DB_PASS: auth-service
      DB_NAME: auth-service
      JWT_SECRET: auth-service
    depends_on:
      - postgres
    networks:
      - microservices_network

# product-service:
#   build: ../../services/product-service
#   ports:
#     - "5001:5001"
#   environment:
#     DB_HOST: postgres
#     DB_PORT: 5432
#     DB_USER: root
#     DB_PASS: root
#     DB_NAME: ecommerce
#     ES_HOST: http://elasticsearch:9200
#   depends_on:
#     - postgres
#     - elasticsearch

# cart-service:
#   build: ../../services/cart-service
#   ports:
#     - "5002:5002"
#   environment:
#     REDIS_HOST: redis
#     REDIS_PORT: 6379
#   depends_on:
#     - redis

# order-service:
#   build: ../../services/order-service
#   ports:
#     - "5003:5003"
#   environment:
#     DB_HOST: postgres
#     DB_PORT: 5432
#     DB_USER: root
#     DB_PASS: root
#     DB_NAME: ecommerce
#   depends_on:
#     - postgres

# payment-service:
#   build: ../../services/payment-service
#   ports:
#     - "5004:5004"
#   environment:
#     DB_HOST: postgres
#     DB_PORT: 5432
#     DB_USER: root
#     DB_PASS: root
#     DB_NAME: ecommerce
#   depends_on:
#     - postgres

# shipping-service:
#   build: ../../services/shipping-service
#   ports:
#     - "5005:5005"
#   environment:
#     DB_HOST: postgres
#     DB_PORT: 5432
#     DB_USER: root
#     DB_PASS: root
#     DB_NAME: ecommerce
#   depends_on:
#     - postgres

# notification-service:
#   build: ../../services/notification-service
#   ports:
#     - "5006:5006"
#   environment:
#     RABBITMQ_HOST: rabbitmq
#     RABBITMQ_PORT: 5672
#   depends_on:
#     - rabbitmq

# review-service:
#   build: ../../services/review-service
#   ports:
#     - "5007:5007"
#   environment:
#     DB_HOST: postgres
#     DB_PORT: 5432
#     DB_USER: root
#     DB_PASS: root
#     DB_NAME: ecommerce
#   depends_on:
#     - postgres

# search-service:
#   build: ../../services/search-service
#   ports:
#     - "5008:5008"
#   environment:
#     ES_HOST: http://elasticsearch:9200
#   depends_on:
#     - elasticsearch

volumes:
  pgdata: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
secrets:
  kong_postgres_password:
    file: ./kong-gateway/POSTGRES_PASSWORD
networks:
  microservices_network:
